export const SECRET_MESSAGE_CREATE_REQUEST = "SECRET_MESSAGE_CREATE_REQUEST";
export const SECRET_MESSAGE_CREATE_SUCCESS = "SECRET_MESSAGE_CREATE_SUCCESS";
export const SECRET_MESSAGE_CREATE_FAIL = "SECRET_MESSAGE_CREATE_FAIL";
export const SECRET_MESSAGE_CREATE_RESET = "SECRET_MESSAGE_CREATE_RESET";

export const SECRET_MESSAGE_DETAILS_REQUEST = "SECRET_MESSAGE_DETAILS_REQUEST";
export const SECRET_MESSAGE_DETAILS_SUCCESS = "SECRET_MESSAGE_DETAILS_SUCCESS";
export const SECRET_MESSAGE_DETAILS_FAIL = "SECRET_MESSAGE_DETAILS_FAIL";

export const SECRET_MESSAGE_DELETE_REQUEST = "SECRET_MESSAGE_DELETE_REQUEST";
export const SECRET_MESSAGE_DELETE_SUCCESS = "SECRET_MESSAGE_DELETE_SUCCESS";
export const SECRET_MESSAGE_DELETE_FAIL = "SECRET_MESSAGE_DELETE_FAIL";
